import type { cities } from "./types";

export const cityByLanguage: cities = {
  en: {
    language: "English",
    code: "en",
    items: {
      airplane: "airplane",
      bank: "bank",
      bicycle: "bicycle",
      bridge: "bridge",
      building: "building",
      bus: "bus",
      car: "car",
      castle: "castle",
      "fire station": "fire station",
      fountain: "fountain",
      hospital: "hospital",
      house: "house",
      library: "library",
      park: "park",
      playground: "playground",
      "police station": "police station",
      restaurant: "restaurant",
      school: "school",
      store: "store",
      street: "street",
      subway: "subway",
      taxi: "taxi",
      "traffic light": "traffic light",
      train: "train",
    },
  },

  es: {
    language: "Español",
    code: "es",
    items: {
      airplane: "avión",
      bank: "banco",
      bicycle: "bicicleta",
      bridge: "puente",
      building: "edificio",
      bus: "autobús",
      car: "coche",
      castle: "castillo",
      "fire station": "estación de bomberos",
      fountain: "fuente",
      hospital: "hospital",
      house: "casa",
      library: "biblioteca",
      park: "parque",
      playground: "parque infantil",
      "police station": "comisaría",
      restaurant: "restaurante",
      school: "escuela",
      store: "tienda",
      street: "calle",
      subway: "metro",
      taxi: "taxi",
      "traffic light": "semáforo",
      train: "tren",
    },
  },

  pt: {
    language: "Português",
    code: "pt",
    items: {
      airplane: "avião",
      bank: "banco",
      bicycle: "bicicleta",
      bridge: "ponte",
      building: "edifício",
      bus: "ônibus",
      car: "carro",
      castle: "castelo",
      "fire station": "bombeiros",
      fountain: "fonte",
      hospital: "hospital",
      house: "casa",
      library: "biblioteca",
      park: "parque",
      playground: "parquinho",
      "police station": "delegacia",
      restaurant: "restaurante",
      school: "escola",
      store: "loja",
      street: "rua",
      subway: "metrô",
      taxi: "táxi",
      "traffic light": "sinal de trânsito",
      train: "trem",
    },
  },

  cs: {
    language: "Čeština",
    code: "cs",
    items: {
      airplane: "letadlo",
      bank: "banka",
      bicycle: "kolo",
      bridge: "most",
      building: "budova",
      bus: "autobus",
      car: "auto",
      castle: "hrad",
      "fire station": "hasičská stanice",
      fountain: "fontána",
      hospital: "nemocnice",
      house: "dům",
      library: "knihovna",
      park: "park",
      playground: "hřiště",
      "police station": "policejní stanice",
      restaurant: "restaurace",
      school: "škola",
      store: "obchod",
      street: "ulice",
      subway: "metro",
      taxi: "taxík",
      "traffic light": "semafory",
      train: "vlak",
    },
  },

  fr: {
    language: "Français",
    code: "fr",
    items: {
      airplane: "avion",
      bank: "banque",
      bicycle: "vélo",
      bridge: "pont",
      building: "bâtiment",
      bus: "bus",
      car: "voiture",
      castle: "château",
      "fire station": "caserne de pompiers",
      fountain: "fontaine",
      hospital: "hôpital",
      house: "maison",
      library: "bibliothèque",
      park: "parc",
      playground: "terrain de jeu",
      "police station": "commissariat",
      restaurant: "restaurant",
      school: "école",
      store: "magasin",
      street: "rue",
      subway: "métro",
      taxi: "taxi",
      "traffic light": "feu de circulation",
      train: "train",
    },
  },

  de: {
    language: "Deutsch",
    code: "de",
    items: {
      airplane: "Flugzeug",
      bank: "Bank",
      bicycle: "Fahrrad",
      bridge: "Brücke",
      building: "Gebäude",
      bus: "Bus",
      car: "Auto",
      castle: "Schloss",
      "fire station": "Feuerwache",
      fountain: "Brunnen",
      hospital: "Krankenhaus",
      house: "Haus",
      library: "Bibliothek",
      park: "Park",
      playground: "Spielplatz",
      "police station": "Polizeiwache",
      restaurant: "Restaurant",
      school: "Schule",
      store: "Geschäft",
      street: "Straße",
      subway: "U-Bahn",
      taxi: "Taxi",
      "traffic light": "Ampel",
      train: "Zug",
    },
  },

  ja: {
    language: "日本語",
    code: "ja",
    items: {
      airplane: "飛行機",
      bank: "銀行",
      bicycle: "自転車",
      bridge: "橋",
      building: "建物",
      bus: "バス",
      car: "車",
      castle: "城",
      "fire station": "消防署",
      fountain: "噴水",
      hospital: "病院",
      house: "家",
      library: "図書館",
      park: "公園",
      playground: "遊び場",
      "police station": "警察署",
      restaurant: "レストラン",
      school: "学校",
      store: "店",
      street: "通り",
      subway: "地下鉄",
      taxi: "タクシー",
      "traffic light": "信号機",
      train: "電車",
    },
  },

  ar: {
    language: "العربية",
    code: "ar",
    items: {
      airplane: "طائرة",
      bank: "بنك",
      bicycle: "دراجة",
      bridge: "جسر",
      building: "مبنى",
      bus: "حافلة",
      car: "سيارة",
      castle: "قلعة",
      "fire station": "محطة إطفاء",
      fountain: "نافورة",
      hospital: "مستشفى",
      house: "منزل",
      library: "مكتبة",
      park: "حديقة",
      playground: "ملعب",
      "police station": "مركز شرطة",
      restaurant: "مطعم",
      school: "مدرسة",
      store: "متجر",
      street: "شارع",
      subway: "مترو",
      taxi: "سيارة أجرة",
      "traffic light": "إشارة مرور",
      train: "قطار",
    },
  },
};
