import type { cities } from "./types";

export const cityByLanguage: cities = {
  en: {
    code: 'en',
    language: 'English',
    items: {
      airplane: 'Airplane',
      bank: 'Bank',
      bicycle: 'Bicycle',
      bridge: 'Bridge',
      bus: 'Bus',
      car: 'Car',
      castle: 'Castle',
      'fire-station': 'Fire Station',
      fountain: 'Fountain',
      hospital: 'Hospital',
      house: 'House',
      library: 'Library',
      playground: 'Playground',
      'police-station': 'Police Station',
      restaurant: 'Restaurant',
      school: 'School',
      street: 'Street',
      subway: 'Subway',
      taxi: 'Taxi',
      'traffic-light': 'Traffic Light',
      train: 'Train'
    }
  },
  es: {
    code: 'es',
    language: 'Español',
    items: {
      airplane: 'Avión',
      bank: 'Banco',
      bicycle: 'Bicicleta',
      bridge: 'Puente',
      bus: 'Autobús',
      car: 'Coche',
      castle: 'Castillo',
      'fire-station': 'Estación de Bomberos',
      fountain: 'Fuente',
      hospital: 'Hospital',
      house: 'Casa',
      library: 'Biblioteca',
      playground: 'Parque Infantil',
      'police-station': 'Comisaría',
      restaurant: 'Restaurante',
      school: 'Escuela',
      street: 'Calle',
      subway: 'Metro',
      taxi: 'Taxi',
      'traffic-light': 'Semáforo',
      train: 'Tren'
    }
  },
  fr: {
    code: 'fr',
    language: 'Français',
    items: {
      airplane: 'Avion',
      bank: 'Banque',
      bicycle: 'Vélo',
      bridge: 'Pont',
      bus: 'Bus',
      car: 'Voiture',
      castle: 'Château',
      'fire-station': 'Caserne de Pompiers',
      fountain: 'Fontaine',
      hospital: 'Hôpital',
      house: 'Maison',
      library: 'Bibliothèque',
      playground: 'Terrain de Jeu',
      'police-station': 'Poste de Police',
      restaurant: 'Restaurant',
      school: 'École',
      street: 'Rue',
      subway: 'Métro',
      taxi: 'Taxi',
      'traffic-light': 'Feu de Circulation',
      train: 'Train'
    }
  },
  de: {
    code: 'de',
    language: 'Deutsch',
    items: {
      airplane: 'Flugzeug',
      bank: 'Bank',
      bicycle: 'Fahrrad',
      bridge: 'Brücke',
      bus: 'Bus',
      car: 'Auto',
      castle: 'Schloss',
      'fire-station': 'Feuerwache',
      fountain: 'Brunnen',
      hospital: 'Krankenhaus',
      house: 'Haus',
      library: 'Bibliothek',
      playground: 'Spielplatz',
      'police-station': 'Polizeiwache',
      restaurant: 'Restaurant',
      school: 'Schule',
      street: 'Straße',
      subway: 'U-Bahn',
      taxi: 'Taxi',
      'traffic-light': 'Ampel',
      train: 'Zug'
    }
  },
  cs: {
    code: 'cs',
    language: 'Čeština',
    items: {
      airplane: 'Letadlo',
      bank: 'Banka',
      bicycle: 'Kolo',
      bridge: 'Most',
      bus: 'Autobus',
      car: 'Auto',
      castle: 'Hrad',
      'fire-station': 'Hasičská Stanice',
      fountain: 'Fontána',
      hospital: 'Nemocnice',
      house: 'Dům',
      library: 'Knihovna',
      playground: 'Hřiště',
      'police-station': 'Policejní Stanice',
      restaurant: 'Restaurace',
      school: 'Škola',
      street: 'Ulice',
      subway: 'Metro',
      taxi: 'Taxík',
      'traffic-light': 'Semafory',
      train: 'Vlak'
    }
  },
  pt: {
    code: 'pt',
    language: 'Português',
    items: {
      airplane: 'Avião',
      bank: 'Banco',
      bicycle: 'Bicicleta',
      bridge: 'Ponte',
      bus: 'Ônibus',
      car: 'Carro',
      castle: 'Castelo',
      'fire-station': 'Estação de Bombeiros',
      fountain: 'Fonte',
      hospital: 'Hospital',
      house: 'Casa',
      library: 'Biblioteca',
      playground: 'Parquinho',
      'police-station': 'Delegacia de Polícia',
      restaurant: 'Restaurante',
      school: 'Escola',
      street: 'Rua',
      subway: 'Metro',
      taxi: 'Táxi',
      'traffic-light': 'Semáforo',
      train: 'Trem'
    }
  },
  ja: {
    code: 'ja',
    language: '日本語',
    items: {
      airplane: '飛行機',
      bank: '銀行',
      bicycle: '自転車',
      bridge: '橋',
      bus: 'バス',
      car: '車',
      castle: '城',
      'fire-station': '消防署',
      fountain: '噴水',
      hospital: '病院',
      house: '家',
      library: '図書館',
      playground: '遊び場',
      'police-station': '警察署',
      restaurant: 'レストラン',
      school: '学校',
      street: '道',
      subway: '地下鉄',
      taxi: 'タクシー',
      'traffic-light': '信号機',
      train: '電車'
    }
  },
  ar: {
    code: 'ar',
    language: 'العربية',
    items: {
      airplane: 'طائرة',
      bank: 'بنك',
      bicycle: 'دراجة',
      bridge: 'جسر',
      bus: 'حافلة',
      car: 'سيارة',
      castle: 'قلعة',
      'fire-station': 'محطة إطفاء',
      fountain: 'نافورة',
      hospital: 'مستشفى',
      house: 'منزل',
      library: 'مكتبة',
      playground: 'ملعب',
      'police-station': 'مركز شرطة',
      restaurant: 'مطعم',
      school: 'مدرسة',
      street: 'شارع',
      subway: 'مترو',
      taxi: 'تاكسي',
      'traffic-light': 'إشارة مرور',
      train: 'قطار'
    }
  }
}
